### ISSUE TITLE
Test Post to Course with the latest WP version and release it

### ISSUE THREAD

**Issue by merkushin** [Automattic/sensei-post-to-course#12]
Currently, on [wordpress.org](https://wordpress.org/plugins/sensei-post-to-course/), we see a message that the plugin might be abandoned:

> This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

We need to test it with the latest WordPress version, update corresponding versions, and release the plugin.

**Comment by donnapep** [comment]
Released [version 1.2.1](https://github.com/Automattic/sensei-post-to-course/milestone/4).
