### ISSUE TITLE
Test with latest WordPress releases and update versions in the plugin

### ISSUE THREAD

**Issue by merkushin** [Automattic/sensei-post-to-course#13]
Test with three latest versions of WordPress.
Update versions to actual ones.

Current versions:

```
Requires at least: 5.7
Tested up to: 5.9
Requires PHP: 7.0
```

Current versions in Sensei LMS:

```
Requires at least: 6.2
Tested up to: 6.4
Requires PHP: 7.4
```

**Comment by StefMattana** [comment]
FTR that was reported by one of our users: https://wordpress.org/support/topic/not-maintained-anymore-2/
